---
title: "03.1_correlation_plt"
author: "Puvvula"
date: "2024-08-07"
output: pdf_document
---

#load SDOH data
```{r}
load(paste0(direc, "SDOH_final.RDA"))
```

#select required variables to work
```{r}
index_df<- dat_fin |>
  as_tibble()|>
  select(c(4, 16:27)) |>
  rename(`Non-Hispanic Black` = blk_pct,
         Hispanic = hisp_pct,
         Asian = asin_pct,
         `Alaska/Pacific-Islander` = alask_pacf_isl_pct,
         `Health insurance` = ins_pct,
         `Federal assistance` =ssi_snap_pct,
         `Households in poverty` = poverty_pct,
         `Un-employment` = un_empl_pct,
         `Language barrier` = langu_pct,
         `Single parent` =sing_prnt_pct,
         `Foregin born` = foregin_born_pct,
         `Access to vechilce` = no_vehic
         )
```

#sequence of variables
```{r}
desired_order <- c("Non-Hispanic Black", "Hispanic", "Asian", "Alaska/Pacific-Islander", 
                   "Households in poverty", "Federal assistance", "Un-employment",
                   "Health insurance", "Language barrier", "Single parent",
                   "Access to vechilce", "Foregin born")
```

################################################################################
################################################################################
#building correlation matrix
################################################################################
################################################################################
```{r}
dat_cor<- index_df |> select(-c(geoid))

cormat <- round(x=cor(dat_cor, method = "spearman", use = "complete.obs"), digits = 2) |>
  melt() |> 
  clean_names() |>
  mutate_at(vars(var1, var2), ~str_replace_all(., "_(?=[A-Z])", " ")) |>
  mutate_at(vars(var1, var2), ~factor(., levels = desired_order))
```

#correlation heatmap
```{r}
ggplot(cormat, aes(x = var2, y = var1, fill = value, label = value)) + #
  geom_tile(color = "white") +
  geom_text(color = "black", size = 3, vjust = 1) +
  scale_fill_gradient2(low = "#D55E00", high = "royalblue", mid = "white",
                       midpoint = 0,
                       limit = c(-1, 1), space = "Lab",
                       name = "Spearman Correlation coefficient") +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, vjust = 1, size = 11, hjust = 1),
        axis.text.y = element_text(angle = 0, vjust = 0.5, size = 11, hjust = 1),
        axis.title.x = element_blank(),
        axis.title.y = element_blank(),
        panel.grid.major = element_blank(),
        panel.border = element_blank(),
        panel.background = element_blank(),
        axis.ticks = element_blank(),
        legend.position = "bottom", legend.box = "horizontal") +
  coord_fixed()+
  geom_vline(xintercept = c(0.5, 4.5, 8.5, 12.5), color = "black", linewidth=1.25) +
  geom_hline(yintercept = c(0.5, 4.5, 8.5, 12.5), color = "black", linewidth=1.25) 
```

#export correlation heatmap
```{r}
ggsave("~/Documents/extreme_heat_cc/mansc_results/sdoh_corrplt.tiff",
       width=8, height= 8, dpi=300)
```

