---
title: "03_testing_maps"
author: "Puvvula"
date: "2024-04-23"
output: pdf_document
---

#get state boundaries
```{r}
state_shp<- states(cb=F) |>
  filter(STUSPS %in% c("AL", "AK", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", 
            "GA", "HI", "ID", "IL", "IN", "IA", "KS", "KY", "LA", 
            "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", 
            "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", 
            "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", 
            "VA", "WA", "WV", "WI", "WY", "DC"))
```

#read processed SDOH data
```{r}
load(paste0(direc, "SDOH_final.RDA"))
```

#long formatting
```{r}
dat_fin_long <- dat_fin |>
  rename(`Non-Hispanic Black` = blk_pct,
         Hispanic = hisp_pct,
         Asian = asin_pct,
         `Alaska/Pacific-Islander` = alask_pacf_isl_pct,
         `Health insurance` = ins_pct,
         `Federal assistance` =ssi_snap_pct,
         `Households in poverty` = poverty_pct,
         `Un-employment` = un_empl_pct,
         `Language barrier` = langu_pct,
         `Single parent` =sing_prnt_pct,
         `Foregin born` = foregin_born_pct,
         `Access to vechilce` = no_vehic
         )|>
  select(c(13, 16:27)) |>
  pivot_longer(cols = -geometry.x, names_to = "variable", values_to = "value")
```

#create boxplots
```{r}
ggplot(dat_fin_long, aes(x = variable, y = value)) +
  geom_boxplot() +
  theme_minimal() +
  xlab("Variable") +
  ylab("Value") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))
```


#sequence for facets
```{r}
desired_order <- c("Non-Hispanic Black", "Hispanic", "Asian", "Alaska/Pacific-Islander", 
                   "Households in poverty", "Federal assistance", "Un-employment",
                   "Health insurance", "Language barrier", "Single parent",
                   "Access to vechilce",
                   "Foregin born")

dat_fin_long$variable <- factor(dat_fin_long$variable, levels = desired_order)
```


# mapping
```{r}
color_palette <- viridis(3, option = "D")
ggplot() +
  geom_sf(data=dat_fin_long, aes(geometry = geometry.x, fill = value), color=NA) + 
  geom_sf(data = state_shp, aes(geometry = geometry), fill= NA, color = "white", size = 8) +
  scale_fill_viridis_c() +  # Use viridis color palette for continuous scale
  theme_void() +
  facet_wrap(~ variable)+
  theme(legend.position = "bottom",
        legend.direction = "horizontal",
        strip.text = element_text(size = 12, face = "bold", angle = 0, hjust = 0.5),
        strip.background = element_blank()) 

ggsave(paste0(result_path, "sdoh_maps_tif.tiff"), 
       width = 16,height = 10,
       dpi=300)
```



