---
title: "05.1_future_cc"
author: "Puvvula"
date: "2024-05-15"
output: pdf_document
---

```{r}
#future climate change
mid_cen_cc <- raster("~/Documents/extreme_heat_cc/data/CONUS/future_cc/midcentury_delta_USA.tif")
late_cen_cc <- raster("~/Documents/extreme_heat_cc/data/CONUS/future_cc/latecentury_delta_USA.tif")

#current climate change
extr_heat <- raster("~/Documents/extreme_heat_cc/data/CONUS/current_cc/overall_trend.tif")

#NOAA-reference file
noaa_extr_heat <- raster("~/Documents/extreme_heat_cc/data/CONUS/NOAA_ref/USASummer_NOAA.tif")
```

```{r}
#extreme_heat - total days = 1,100 (June 1st - August 31 over 2012 to 2022)
extr_heat_df <- as.data.frame(extr_heat, xy = TRUE) |>
  rename(ext_ht_cnt = overall_trend) |>
  filter(ext_ht_cnt != 0)

#NOAA reference file - total days = 1,100 (June 1st - August 31 over 2012 to 2022)
noaa_extr_heat_df <- as.data.frame(noaa_extr_heat, xy = TRUE) |>
  rename(ext_ht_cnt = USASummer_NOAA) |>
  filter(ext_ht_cnt != 0)
  

#2030-2064
mid_cen_cc_df <- as.data.frame(mid_cen_cc, xy = TRUE)|>
  rename(mid_cen_delta = midcentury_delta_USA) |>
  filter(mid_cen_delta != 0)

#2065-2099
late_cen_cc_df <- as.data.frame(late_cen_cc, xy = TRUE)|>
  rename(late_cen_delta = latecentury_delta_USA) |>
  filter(late_cen_delta != 0)

```

```{r}
state_shp<- states(cb=F) |>
  filter(!STUSPS %in% c("AK", "HI", "GU", "VI", "MP", "AS", "PR"))

cities <- data.frame(
  city = c("New York", "Los Angeles", "Chicago", "Houston", "Phoenix", "Philadelphia", 
           "San Antonio", "San Diego", "Dallas", "San Jose", "Austin", "Jacksonville", 
           "Fort Worth", "Columbus", "Charlotte", "San Francisco", "Indianapolis", "Seattle", 
           "Denver", "Washington"),
  state = c("NY", "CA", "IL", "TX", "AZ", "PA", 
            "TX", "CA", "TX", "CA", "TX", "FL", 
            "TX", "OH", "NC", "CA", "IN", "WA", 
            "CO", "DC"),
  x = c(-74.0060, -118.2437, -87.6298, -95.3698, -112.0740, -75.1652, 
        -98.4936, -117.1611, -96.7970, -121.8863, -97.7431, -81.6557, 
        -97.3327, -82.9988, -80.8431, -122.4194, -86.1581, -122.3321, 
        -104.9903, -77.0369),
  y = c(40.7128, 34.0522, 41.8781, 29.7604, 33.4484, 39.9526, 
        29.4241, 32.7157, 32.7767, 37.3382, 30.2672, 30.3322, 
        32.7555, 39.9612, 35.2271, 37.7749, 39.7684, 47.6062, 
        39.7392, 38.9072)
)
```


#prelim plots

##current climate change
```{r}
current_cc<- 
  ggplot()+
  geom_raster(data = extr_heat_df, aes(x = x, y = y, fill = ext_ht_cnt))+
  geom_sf(data = state_shp, aes(geometry = geometry), fill= NA, color = "white", size = 20,  show.legend = F)+
  geom_point(data = cities, aes(x = x, y = y), color = "yellow", size = 2,  show.legend = F) +
  scale_fill_viridis(option="A") +
  theme_void() +
  theme(legend.position = "bottom")+
  guides(fill = guide_colorbar("Frequency of hot days 2012-2022"))+
  theme(legend.position.inside = c(0.7, 0.1),  # Custom position (x, y)
        legend.justification = c(2.4, 0),
        legend.direction = "horizontal")   # Anchor point (right, bottom)
```

#city specific plots
```{r}
current_cc <-
  ggplot() +
  geom_raster(data = extr_heat_df, aes(x = x, y = y, fill = ext_ht_cnt)) +
  geom_sf(data = state_shp, aes(geometry = geometry), fill = NA, color = "white", size = 0.5, show.legend = FALSE) +
  geom_point(data = cities, aes(x = x, y = y), color = "yellow", size = 2, show.legend = FALSE) +
  scale_fill_viridis(option = "A", limits = c(0, 600)) +
  theme_void() +
  guides(fill = guide_colorbar("Warming trend 2012-2022")) +
  theme(legend.text = element_text(angle = 45),
        legend.position = "bottom",
        legend.justification = "center",
        legend.direction = "horizontal",
        plot.margin = unit(c(1, 1, 4, 1), "lines")  # Increase bottom margin for the legend
        ) +
  coord_sf(
    xlim = c(-75.3, -75.0), 
    ylim = c(39.8, 40.2)
)

# Draw the plot with the legend positioned outside at the bottom
grid::grid.draw(current_cc + theme(legend.position = "bottom"))
```


```{r}
ggsave(current_cc,
       file="~/Documents/extreme_heat_cc/results/CONUS/extreme_heat_US.tiff",
       width = 14,height = 10,
       dpi=100)
```

##Future climate change - Mid century (2030-2064)
```{r}
mid_century_delta<- 
  ggplot()+
  geom_raster(data = mid_cen_cc_df, aes(x = x, y = y, fill = mid_cen_delta))+
  geom_sf(data = state_shp, aes(geometry = geometry), fill= NA, color = "white", size = 20,  show.legend = F)+
  geom_point(data = cities, aes(x = x, y = y), color = "yellow", size = 2,  show.legend = F) +
  scale_fill_viridis(option="A") +
  theme_void() +
  theme(legend.position = "bottom")+
  guides(fill = guide_colorbar("Mid century \u0394 RCP8.5-RCP4.5"))+
  theme(legend.position = c(0.7, 0.1),  # Custom position (x, y)
        legend.justification = c(2.4, 0),
        legend.direction = "horizontal")   # Anchor point (right, bottom)
```

```{r}
ggsave(mid_century_delta,
       file="~/Documents/extreme_heat_cc/results/CONUS/mid_cen_delta.tiff",
       width = 14,height = 10,
       dpi=100)
```

##Future climate change - Late Century (2065-2099)
```{r}
late_century_delta<- 
  ggplot()+
  geom_raster(data = late_cen_cc_df, aes(x = x, y = y, fill = late_cen_delta))+
  geom_sf(data = state_shp, aes(geometry = geometry), fill= NA, color = "white", size = 20,  show.legend = F)+
  geom_point(data = cities, aes(x = x, y = y), color = "yellow", size = 2,  show.legend = F) +
  scale_fill_viridis(option="A") +
  theme_void() +
  theme(legend.position = "bottom")+
  guides(fill = guide_colorbar("Late century \u0394 RCP8.5-RCP4.5"))+
  theme(legend.position = c(0.7, 0.1),  # Custom position (x, y)
        legend.justification = c(2.4, 0),
        legend.direction = "horizontal")   # Anchor point (right, bottom)
```

```{r}
ggsave(late_century_delta,
       file="~/Documents/extreme_heat_cc/results/CONUS/late_cen_delta_hdef.tiff",
       width = 14,height = 10,
       dpi=600)
```


