---
title: "06_bivariate_map"
author: "Puvvula"
date: "2024-07-09"
output: pdf_document
---

```{r}
library(pacman)
pacman::p_load(tidyverse, tidycensus, janitor, glue, httr, terra, fs, httr, 
               ncdf4, raster, stringr, sf, broom, biscale,
               tigris, cowplot, ggpattern)
```

#census tract shapefile
```{r}
tracts_conus <- get_acs(geography = "tract", #census block group
        state = c("AL", "AZ", "AR", "CA", "CO", "CT", "DE", "FL", 
                  "GA", "ID", "IL", "IN", "IA", "KS", "KY", "LA", 
                  "ME", "MD", "MA", "MI", "MN", "MS", "MO", "MT", "NE", 
                  "NV", "NH", "NJ", "NM", "NY", "NC", "ND", "OH", "OK", 
                  "OR", "PA", "RI", "SC", "SD", "TN", "TX", "UT", "VT", 
                  "VA", "WA", "WV", "WI", "WY", "DC"),
        year=2021,
        survey = "acs5",
        variables=c(total_pop = "B01001A_001"),
        geometry = T,
        output = "wide") %>% clean_names()

#save census tract shape file
st_write(tracts_conus, "D:/cc_vulnerability/tracts_shp/tracts_conus_shape.shp",
         delete_dsn = TRUE)
```

#final version of vulnerability index - created on June 3, 2024
```{r}
tracts_conus <- st_read("D:/cc_vulnerability/tracts_shp/tracts_conus_shape.shp") |>
  dplyr::select(c(1, 5))

ped_indx <- read_csv("D:/cc_vulnerability/mansc_results/index_vars/all_indicies_combined.csv") |>
  dplyr::select(c(1, 14)) |>
  right_join(tracts_conus, by= "geoid") 

# First, make sure ped_indx is an sf object with geometry
if (!("sf" %in% class(ped_indx))) {
  # If it lost its sf class during the join, convert it back
  ped_indx <- st_as_sf(ped_indx)
}

# Set the CRS to NAD83 (EPSG:4269)
ped_indx <- st_set_crs(ped_indx, 4269)  # EPSG code for NAD83
```

#current anomalies file
```{r}
curr_anom<- raster("D:/cc_vulnerability/exceed_count_results/total_exceed_days_2012_2024.tif")

# Convert raster to terra format
curr_anom_terra <- terra::rast(curr_anom)
```

#join pediatric indicies and temperature anomalies 
```{r}
# Now transform to match the raster's CRS (WGS84)
ped_indx_transformed <- st_transform(ped_indx, crs(curr_anom_terra))

# Convert to a terra vector object
vector_terra <- vect(ped_indx_transformed)

# Choose the appropriate column (adjust based on the output above)
field_to_use <- names(vector_terra)[2]  # Change index as needed

# Rasterize the vector data to match the raster's resolution
result_raster <- rasterize(vector_terra, curr_anom_terra, field=field_to_use)

# Create a multi-layer raster by stacking both layers
combined_raster <- c(curr_anom_terra, result_raster)

# Set appropriate names for the layers
names(combined_raster) <- c("total_exceed_days_2012_2024", "PC1")

# Save the multi-layer raster
#writeRaster(combined_raster, "D:/cc_vulnerability/mansc_results/current_anomalies_bivar/vulnerability_raster.tif",  overwrite=TRUE)

#save(combined_raster, file = "D:/cc_vulnerability/mansc_results/current_anomalies_bivar/combined_raster.RDA")
```


```{r}
# Create a data frame from the combined raster that has both variables
bivariate_raster_df <- as.data.frame(combined_raster, xy = TRUE) |>
  filter(!is.na(total_exceed_days_2012_2024), 
         !is.na(PC1)) |>
  bi_class(x=PC1, 
           y=total_exceed_days_2012_2024,
           style = "quantile",
           dim = 3)
```

#RUCA codes
```{r}
load("D:/cc_vulnerability/ruca_sf.rda") 

ruca_shp <- ruca_shp |>
  mutate(ruca_category = case_when(
    prima_ruca %in% 1:3 ~ "Metropolitan",
    prima_ruca %in% 4:6 ~ "Micropolitan",
    prima_ruca %in% 7:10 ~ "Small_town_Rural",
    prima_ruca == 99 ~ NA_character_,
    TRUE ~ NA_character_
  )) |>
  drop_na() |>
  filter(ruca_category == "Small_town_Rural")

# Set the CRS to NAD83 (EPSG:4269)
ruca_shp_sf <- st_set_crs(ruca_shp, 4269)  # EPSG code for NAD83
```

#State shapefile
```{r}
state_shp<- tigris::states(cb=F) |>
  filter(!STUSPS %in% c("AK", "HI", "GU", "VI", "MP", "AS", "PR"))
```


#bivariate plotting - CONUS
#nclimgrid anomalies and PC1
```{r}
map <- ggplot() +
  geom_raster(data = bivariate_raster_df, 
              aes(x = x, y = y, fill = bi_class), 
              show.legend = FALSE) +
  geom_sf(data = state_shp, 
          aes(geometry = geometry), 
          fill = NA, color = "white",
          size = 12,  
          show.legend = FALSE) +
  geom_sf_pattern(data = ruca_shp_sf,
                  aes(geometry = geometry, pattern = ruca_category),
                  fill = NA,
                  color = NA,
                  pattern_fill = "white",
                  pattern_density = 0.45,
                  pattern_spacing = 0.01,
                  pattern_angle = 45,
                  pattern_size = 0.0001,
                  pattern_alpha = 0.05,
                  show.legend = FALSE) +
  labs(x = NULL, y = NULL) +
  bi_scale_fill(pal = "DkBlue2", dim = 3) +
  theme_void() +
  theme(legend.position = "none") +
  bi_theme()

tiff(
  filename = "D:/cc_vulnerability/results_apr_2025/bivariate_map_pc1_heat.tiff",
  width = 12, height = 10, units = "in", 
  res = 100,
  compression = "lzw"
)

print(map)

dev.off()

```


```{r}
legend <- bi_legend(pal = "DkBlue2",
                   dim = 3,
                   xlab = "Pediatric vulnerability",
                   ylab = "Tmax anomalies",
                   size = 10)

ggsave("D:/cc_vulnerability/results_apr_2025/legend_component.tiff", 
       plot = legend, 
       width = 6, height = 3, 
       dpi = 300, 
       device = "tiff", 
       compression = "lzw")
```



